### ISSUE TITLE
Tutorial 8 not working in OpenGL

### ISSUE THREAD

**Issue by niccoloo** [DiligentGraphics/DiligentSamples#103]
The tutorial 8 (tessellation) doesn't render correctly when using the OpenGL backend, neither on Windows nor on Mac. It works fine with other backends.

**On Windows**: most tiles are not visible, and some of them randomly appear and disappear soon after.
Windows 11 21H2 / Visual Studio 2022 Release x64 / CMake 3.21.3
AMD Radeon RX 6600 XT / driver version 30.0.14023.1009

![Screenshot](https://user-images.githubusercontent.com/17908966/179779028-1057b8a6-58ba-4291-9a0b-8abed0840764.png)

**On Mac**:
MacBookPro 16,1 / macOS 11.6.5
AMD Radeon Pro 5500M/Intel UHD Graphics 630
<img width="912" alt="Capture d’écran 2022-07-19 à 15 16 13" src="https://user-images.githubusercontent.com/17908966/179779984-35e53e18-2f5e-4f94-b85f-c2fb705749b4.png">

**Comment by TheMostDiligent** [comment]
This could be AMD driver bug. This tutorial works properly in OpenGL mode on Nvidia, Intel, M1, Android ARM GPUs

**Comment by TheMostDiligent** [comment]
We tested this on AMD Radeon 6800m it works fine. Can you try to update the drivers and retest?
