### ISSUE TITLE
Pipeline state update

### ISSUE THREAD

**Issue by MPcoreDev** [DiligentGraphics/DiligentSamples#112]
Hello
I wonder what is the best way to update a pipeline state object ? Is it possible ?
The need is that - for dev and debug purpose - I want to have the ability to toggle on/off at runtime some pipeline properties like depth testing, backface culling...
Is there a way to change that dynamically in a given PipelineState or do I need to create a new one by copy and update the properties as desired ?
Thanks for advices,
JD

**Comment by TheMostDiligent** [comment]
The whole idea behind the pipeline state objects is that they are immutable, so that the driver can perform all required optimizations, shader compilation and validation checks up-front to avoid run-time stutters.
You can't change any of the properties of the PSO and need to create a new one.
