### ISSUE TITLE
 tutorial00_win32 and tutorial02_cube, the different of executable file size is huge

### ISSUE THREAD

**Issue by jiacpt** [DiligentGraphics/DiligentSamples#115]
** I wonder if this is normal **

![image](https://github.com/DiligentGraphics/DiligentSamples/assets/60881887/1251b517-b539-4c84-9101-3c3a3ca1f351)

![image](https://github.com/DiligentGraphics/DiligentSamples/assets/60881887/d101c740-229b-4428-9de8-2b9f5f6a6f6a)

**Compiler:**
GCC-11.2.0

**OS:**
window11

**CPU**
![image](https://github.com/DiligentGraphics/DiligentSamples/assets/60881887/1c1f7f9b-ac5e-40d6-bfe5-6ca564e1f23c)
and no independent gpu

-  when i compile code is normal, but link tutorial02 is spend long time

**Comment by TheMostDiligent** [comment]
Don't use gcc on Windows. Build with MSVC
