### ISSUE TITLE
All samples and tutorials can't run (crash) under macOS with Molten Vulkan

### ISSUE THREAD

**Issue by hyv1001** [DiligentGraphics/DiligentSamples#139]
![image](https://github.com/DiligentGraphics/DiligentSamples/assets/102242553/ff884f79-cfd7-4485-adf0-cb0f5a7149bf)

Only the Vulkan backend has issues, the OpenGL backend works fine.

- OS: macOS 14.3.1 (23D60), Apple M1
- Xcode: Version 15.2 (15C500b)
- Vulkan SDK: 1.3.275.0

If ignore this check, the App will still crash:

![image](https://github.com/DiligentGraphics/DiligentSamples/assets/102242553/bfa677cf-aec3-4803-97de-244a3c2cf062)

**Comment by hyv1001** [comment]
Solved by set VK_LAYER_PATH enviornment variable
`export VK_LAYER_PATH=$VULKAN_SDK/etc/vulkan/explicit_layer.d`

**Comment by TheMostDiligent** [comment]
Did you follow these steps:

**Comment by hyv1001** [comment]
> Did you follow these steps: https://github.com/DiligentGraphics/DiligentEngine?tab=readme-ov-file#configuring-vulkan-build-environment

Yes

These samples could work in version 1.3.250.1 of Vulkan SDK, but not in the latest version (1.3.275.0)

**Comment by TheMostDiligent** [comment]
OK, we will take a look. This is not the first time when new version of MoltenVK is not backwards-compatible.

**Comment by TheMostDiligent** [comment]
https://github.com/KhronosGroup/MoltenVK/issues/2226

**Comment by TheMostDiligent** [comment]
Fixed in https://github.com/DiligentGraphics/DiligentEngine/commit/8e2739e64fc165d97465d2e631ca973ce4695853
