### ISSUE TITLE
Enable Windows 7 support

### ISSUE THREAD

**Issue by KoromaruKoruko** [DiligentGraphics/DiligentSamples#14]
I'm using VS2019 on WIN7 I just built the AtmosphereSample demo but once I start it and select a renderer it crashes, no matter which renderer I choose. it comes up with:

> Unhandled exception at 0x000007FED4AF0667 (GraphicsEngineD3D11_64r.dll) in AtmosphereSample.exe: 0xC000001D: Illegal Instruction.

how do I get this fixed?
I have tried (in order):
all the different renderer options except D3D12 (DirectX12),
Rebuilding the solution,
retrying all render options except D3D12,
Running it with admin privs.

**Comment by DiligentGraphics** [comment]
Hello! Not sure about Win7. Can you try to generate solution files for win8.1 SDK?

https://github.com/DiligentGraphics/DiligentEngine/blob/master/README.md#win32

**Comment by dedady157** [comment]
i have generated all the files im trying to compile and run them but when i run them that happens

**Comment by DiligentGraphics** [comment]
Can you try to build the debug configuration? There may be something useful in debug output.

**Comment by dedady157** [comment]
the same thing is happening

**Comment by DiligentGraphics** [comment]
And nothing in debug output? There should be at least something. It seems like the system can't find some all.

**Comment by dedady157** [comment]
ill recompile everything with the defualt CMAKE configs just with d3d12 disabled

**Comment by dedady157** [comment]
![image](https://user-images.githubusercontent.com/17232928/57409258-1f1f3100-71e8-11e9-954f-69c61d2edbe6.png)

**Comment by dedady157** [comment]
basically everything is uninitialized/undefined

**Comment by DiligentGraphics** [comment]
Ah, I guess this is because the swap chain initialization requests an interface that is not supported on Win7. Did you try OpenGL or Vulkan mode? OpenGL especially

**Comment by dedady157** [comment]
yes, I have and ill double check to make sure the drivers and any on system software is up to date and working.

**Comment by dedady157** [comment]
wait nvm, I just have the drivers for Vulkan but it isn't actually supported by my graphics card

**Comment by DiligentGraphics** [comment]
What about OpenGL? Does it work?

**Comment by dedady157** [comment]
I'm still getting a version of OpenGL downloaded and making a demo program

**Comment by DiligentGraphics** [comment]
Ok, at least something works, good.

D3D11 doesn't work because the engine requires an interface that is not supported on Windows 7. Will need to see if swap chain initialization can be implemented with older interfaces.
It is strange though that Vulkan doesn't work. Do you have the latest drivers?

**Comment by dedady157** [comment]
I have an MSI R7 370, which doesn't support Vulkan sadly

**Comment by dedady157** [comment]
So I have gone ahead and just upgraded to win 10, but you might as well see about adding support for win7 since a large amount of people are still on there

**Comment by TheMostDiligent** [comment]
Closing this issue as [Microsoft does not support Windows 7 anymore](https://support.microsoft.com/en-us/help/4057281/windows-7-support-ended-on-january-14-2020).
