### ISSUE TITLE
Tutorial 22: Incorrect rendering on D3D12

### ISSUE THREAD

**Issue by MikhailGorobets** [DiligentGraphics/DiligentSamples#155]
Demo does not render correctly on RTX 4090 mobile
![image](https://github.com/DiligentGraphics/DiligentSamples/assets/25492259/8038a6cf-f3b7-4fa1-874b-96e7105502fc)

**Comment by TheMostDiligent** [comment]
Fixed in https://github.com/DiligentGraphics/DiligentEngine/commit/a2f6940c47088d41b4bc4bcf2a58e8d01bae0402
