### ISSUE TITLE
Tutorial 22: Crash on D3D12

### ISSUE THREAD

**Issue by MikhailGorobets** [DiligentGraphics/DiligentSamples#156]
When launching this demo on Radeon 610m, an error occurs
![image](https://github.com/DiligentGraphics/DiligentSamples/assets/25492259/cf069d8f-cd4a-4349-b829-eb087cf209b7)

**Comment by TheMostDiligent** [comment]
Fixed in https://github.com/DiligentGraphics/DiligentEngine/commit/a2f6940c47088d41b4bc4bcf2a58e8d01bae0402
