### ISSUE TITLE
[Tutorial 24 VRS, Turorial 20 Mesh Shader]: Crash on D3D12

### ISSUE THREAD

**Issue by MikhailGorobets** [DiligentGraphics/DiligentSamples#157]
When launching the applications on RTX 4090 Mobile, an error occurs in nvwgf2umx.dll during PSO creation

**Comment by TheMostDiligent** [comment]
Fixed in https://github.com/DiligentGraphics/DiligentEngine/commit/a2f6940c47088d41b4bc4bcf2a58e8d01bae0402
