### ISSUE TITLE
Replace AntTweakBar with imgui

### ISSUE THREAD

**Issue by DiligentGraphics** [DiligentGraphics/DiligentSamples#16]
AntTweakBar is not maintained anymore and renders very slowly. Imgui seems to be a much better alternative.

**Comment by zlixine** [comment]
I have already ported ImGui to Diligent, Feel free to use the [port](https://github.com/Zone-organization/Nuclear-Engine/blob/master/Nuclear%20Engine/Source/Engine/Graphics/ImGUI/imgui_impl.cpp)

BTW, it lacks real resource deletion in `ImGui_Impl_InvalidateDeviceObjects` but I really don't know how to release a resource manually, so be sure to check that out.

**Comment by DiligentGraphics** [comment]
@zlixine Thanks! Will take a look!

**Comment by DiligentGraphics** [comment]
Looks like [nuklear](https://github.com/vurtun/nuklear) might be a better option

**Comment by DiligentGraphics** [comment]
Imgui is now the main UI
