### ISSUE TITLE
Samples and Tutorials Abort

### ISSUE THREAD

**Issue by fredlangva** [DiligentGraphics/DiligentSamples#18]
I have successfully built the engine on vs2017, win10. When I run any of the samples or tutorials, the main window context starts and the aborts before any content is started. No messages are displayed on the command prompt window.

**Comment by DiligentGraphics** [comment]
If you run applications from the command line, the assets folder must be made current directory
https://github.com/DiligentGraphics/DiligentEngine#win32

**Comment by fredlangva** [comment]
move the assets folder for Tutorial00_HelloWin32 into the release folder where the executable is. cd to assets and run the exe from the release folder (..\tutorial00_hellowin32) . Still had the same result. BTW, the assets folder for the 00 tut was blank. it looks like the engine is having an exception.

**Comment by fredlangva** [comment]
built in debug, exception is no suitable graphics adapter found.  dxdiag reports dx12 is installed.

**Comment by DiligentGraphics** [comment]
What GPU do you have? Do other backends work?

**Comment by olegviz** [comment]
Could be that you have 2 graphics adapters ? , and the onboard adapter that
initialized first is not working .

**Comment by fredlangva** [comment]
Apparently, my graphics card does not support dx12 even though it loads and tests ok. I'll try making a test program from scratch. Ok to close

**Comment by DiligentGraphics** [comment]
@fredlangva You can also try to run Microsoft D3D12 samples:
https://github.com/microsoft/DirectX-Graphics-Samples/tree/master/Samples/Desktop
