### ISSUE TITLE
Asteroids sample crashing

### ISSUE THREAD

**Issue by olegviz** [DiligentGraphics/DiligentSamples#2]
Diligent Engine: ERROR: Space in dynamic heap is exausted! After idling for 60.3 ms still no space is available. Increase the size of the heap by setting EngineVkAttribs::DynamicHeapSize to a greater value or optimize dynamic resource usage
DiAssertion failed: pDestination, file c:\program files (x86)\windows kits\10\include\10.0.17134.0\um\directxmathconvert.inl, line 1819
ligent Engine: ERROR: Space in dynamic heap is exausted! After idling for 60.3 ms still no space is available. Increase the size of the heap by setting EngineVkAttribs::DynamicHeapSize to a greater value or optimize dynamic resource usage
Assertion failed: pDestination, file c:\program files (x86)\windows kits\10\include\10.0.17134.0\um\directxmathconvert.inl, line 1819

**Comment by TheMostDiligent** [comment]
This seems to be working in the latest - fee free to reopen if the issue persists.
