### ISSUE TITLE
 Diligent::ShaderGLImpl::ShaderGLImpl() (ShaderGLImpl.cpp, 127): Failed to compile shader file

### ISSUE THREAD

**Issue by puyd** [DiligentGraphics/DiligentSamples#22]
Diligent Engine: ERROR in Diligent::ShaderGLImpl::ShaderGLImpl() (ShaderGLImpl.cpp, 127): Failed to compile shader file 'Imgui PS'
InfoLog:
Fragment shader failed to compile with the following errors:
ERROR: 0:205: error(#229) Overloaded functions must have the same return type: unsigned int
ERROR: 0:209: error(#229) Overloaded functions must have the same return type: uvec2
ERROR: 0:214: error(#229) Overloaded functions must have the same return type: uvec3
ERROR: 0:218: error(#229) Overloaded functions must have the same return type: uvec4
ERROR: error(#273) 4 compilation errors.  No code generated

**Comment by TheMostDiligent** [comment]
This is a known problem (https://github.com/DiligentGraphics/DiligentFX/issues/2). These errors are not legitimate and are result of the issue in AMD driver. Try updating the driver, maybe they fixed it. Otherwise there is no easy workaround for this problem.
