### ISSUE TITLE
Assimp support

### ISSUE THREAD

**Issue by bondarenko-me** [DiligentGraphics/DiligentSamples#23]
Hello. First of all, thank you guys, great job 👏.

Second, it's 2020 and a good time to think about extended mesh loading. I tried to link Diligent Graphics Engine (D3D11) with **Assimp** (on Windows), but that's quite wayward. Of course, the library is low-level, however Diligent Samples repo can afford this kind of job.

**Comment by TheMostDiligent** [comment]
There was an idea to use Assimp initially. However, Assimp is quite large project and including it into the main repo would mean quite a lot of extra support (Diligent currently runs on 6 platforms) without clear benefit.
The emphasis of the project is on low-level API and rendering components (such as shadows, post effects etc.). Asset loading is orthogonal to graphics and the expectation is that client applications should be able to implement its own or use existing solutions (such Assimp).

What was your issue with Assimp BTW?

**Comment by bondarenko-me** [comment]
Simply, I wanted to load an .obj mesh (index/vertex buffers) into Diligent::IBuffer + its textures with old good DDS Texture Loader, and then render it with D3D11 (my videocard does not respond when opening OpenGL 4.0+ apps, so I didn't use it).

It was clear however, it is possible with glfw3 so far, and even if Assimp can be integrated into an app with D3D only, it takes a lot of time to make it work (materials, shaders, lights etc) on Direct3D 11/12. So, what can be done in this case?

**Comment by TheMostDiligent** [comment]
There is an example that shows how to load and render GLTF2.0 models. So you can convert obj to gltf and render it with this example, or you can load the obj model similar to how GLTF2.0 loader does it.

**Comment by bondarenko-me** [comment]
Alright, that sounds perfect, I'm gonna try it out. Thank you for clarifying.
