### ISSUE TITLE
Almost every sample broken and crashes, Nvidia

### ISSUE THREAD

**Issue by danilw** [DiligentGraphics/DiligentSamples#25]
**OS, GPU:**
Linux, Nvidia driver 440.82, Nvidia 750
DiligentSamples source and build today.
No changes to Samples.

**Debug output:**

### 1. **Black screen problem** - after launching few Tutorials, form basic *Tutorial01_HelloTriangle* to next, after few launches every DiligentSamples become broken, the black screen always on every Tutorial start from *Tutorial03_Texturing* and all next.
At the same time, every other "demo" (Khronos Vulkan Samples) keeps working without any problems.

Tutorial03_Texturing - [log link](https://pastebin.com/G82LjymB), worked only once

Tutorial18_Queries - [log link](https://pastebin.com/hbi8XeUk), black screen most of the times

**Video proof:**
launching Tutorial17_MSAA and msaa from Khronos samples
[webm video link](https://danilw.github.io/GLSL-howto/vulkan_sh_launcher/diligent_engine_vulkan.webm)

### 2. **Changing shadow settings** in any of *Samples/Atmosphere*,  *Samples/Shadows* result memory leak, I think (maybe im wrong)

**Video proof:**
(for some reason OBS lag on recording DiligentSamples, I do not have lags launching it, video lags)
[webm video link](https://danilw.github.io/GLSL-howto/vulkan_sh_launcher/DiligentSamples_Atmosphere.webm)

watch video, I set all settings to max (2048 textures) then changing *Num cascades* result crash because of, log:

```
Diligent Engine: Info: VulkanMemoryManager 'Global resource memory manager': created new device-local page. (128.00 MB, type idx: 7). Current allocated size: 1.06 GB
Diligent Engine: Info: VulkanMemoryManager 'Global resource memory manager': created new device-local page. (128.00 MB, type idx: 7). Current allocated size: 1.19 GB
Diligent Engine: Info: VulkanMemoryManager 'Global resource memory manager': created new device-local page. (128.00 MB, type idx: 7). Current allocated size: 1.31 GB
Diligent Engine: Info: VulkanMemoryManager 'Global resource memory manager': destroying device-local page (64.00 MB). Current allocated size: 1.25 GB
Diligent Engine: Info: VulkanMemoryManager 'Global resource memory manager': destroying device-local page (64.00 MB). Current allocated size: 1.19 GB
Diligent Engine: Info: VulkanMemoryManager 'Global resource memory manager': destroying device-local page (64.00 MB). Current allocated size: 1.12 GB
Diligent Engine: Info: VulkanMemoryManager 'Global resource memory manager': destroying device-local page (128.00 MB). Current allocated size: 1.00 GB
Diligent Engine: Info: VulkanMemoryManager 'Global resource memory manager': created new device-local page. (128.00 MB, type idx: 7). Current allocated size: 1.12 GB
Diligent Engine: Info: VulkanMemoryManager 'Global resource memory manager': created new device-local page. (128.00 MB, type idx: 7). Current allocated size: 1.25 GB
Diligent Engine: Info: VulkanMemoryManager 'Global resource memory manager': created new device-local page. (128.00 MB, type idx: 7). Current allocated size: 1.38 GB
Diligent Engine: Info: VulkanMemoryManager 'Global resource memory manager': destroying device-local page (128.00 MB). Current allocated size: 1.25 GB
Diligent Engine: Info: VulkanMemoryManager 'Global resource memory manager': destroying device-local page (128.00 MB). Current allocated size: 1.12 GB
Diligent Engine: Info: VulkanMemoryManager 'Global resource memory manager': destroying device-local page (128.00 MB). Current allocated size: 1.00 GB
Diligent Engine: Info: VulkanMemoryManager 'Global resource memory manager': created new device-local page. (128.00 MB, type idx: 7). Current allocated size: 1.12 GB
Diligent Engine: Info: VulkanMemoryManager 'Global resource memory manager': created new device-local page. (128.00 MB, type idx: 7). Current allocated size: 1.25 GB
Diligent Engine: Info: VulkanMemoryManager 'Global resource memory manager': created new device-local page. (128.00 MB, type idx: 7). Current allocated size: 1.38 GB
Diligent Engine: ERROR in AllocateDeviceMemory() (VulkanLogicalDevice.cpp, 176): Failed to allocate device memory 'Device memory page. Size: 128.00 MB, type: 7'
VK Error Code: ERROR_OUT_OF_DEVICE_MEMORY
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to allocate device memory 'Device memory page. Size: 128.00 MB, type: 7'
VK Error Code: ERROR_OUT_OF_DEVICE_MEMORY

```

**Comment by TheMostDiligent** [comment]
It looks like there is a synchronization issue that forces the engine allocate more and more memory until it runs out of memory.
Can you try to update the driver to the latest version (450.57)?

**Comment by danilw** [comment]
>Can you try to update the driver to the latest version (450.57)?

I have tried just now, latest Nvidia driver 450.57 does not work with 5.6 kernel
updating to 5.7 kernel result kernel panic because they have a bug with Ryzen CPU and integrated AMD GPU

so I can not do it now

**Comment by TheMostDiligent** [comment]
Maybe try 440.100?
I honestly don't know what causes the problem, nobody has reported similar issues.
Can you try to enable Vulkan validation layers?

**Comment by danilw** [comment]
>Can you try to enable Vulkan validation layers?

More advance debugging:

1. after rebooting and clean launch Tutorial01_HelloTriangle (no other apps launched) it works, but **launching any two DiligentSamples** make second broken(black screen), also full UI lag very hard(like 1-5 fps outside Vulkan window)
2. launching many Vulkan software (Khronos samples) all at once - do not have any problems, every window work, only two DiligentSamples can not work together
3. on this GPU DXVK do work with complex DX11 games without problems, this is not GPU or my system side problem, yes maybe its Bug in drivers

so **maybe its X11 bug that DiligentSamples trigger**

**Launching with validation layers**

0. I noticed that VSync check do nothing(FPS did not change it always around 50 fps)

1. without *validation layers* I can not launch even two `Tutorial01_HelloTriangle` (second is black screen already)
with enabled *validation layers* **I can launch even 3 windows** with Tutorial01_HelloTriangle, but UI lag impossible hard, FPS in all window is 50 (monitor refresh 60Hz), validation layers report no error

2. starting only from `Tutorial17_MSAA` and all next examples have a black screen with *validation layers* (first window already with black screen)
Validation layer log:
```
VUID-vkResetFences-pFences-01123(ERROR / SPEC): msgNum: 0 - VkFence 0x6d000000006d[] is in use. The Vulkan spec states: Each element of pFences must not be currently associated with any queue command that has not yet completed execution on that queue (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkResetFences-pFences-01123)
    Objects: 1
        [0] 0x6d000000006d, type: 7, name: NULL
VUID-vkResetCommandBuffer-commandBuffer-00045(ERROR / SPEC): msgNum: 0 - Attempt to reset VkCommandBuffer 0x20b3130[] which is in use. The Vulkan spec states: commandBuffer must not be in the pending state (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkResetCommandBuffer-commandBuffer-00045)
    Objects: 1
        [0] 0x20b3130, type: 6, name: NULL
VUID-vkResetFences-pFences-01123(ERROR / SPEC): msgNum: 0 - VkFence 0x720000000072[] is in use. The Vulkan spec states: Each element of pFences must not be currently associated with any queue command that has not yet completed execution on that queue (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkResetFences-pFences-01123)
    Objects: 1
        [0] 0x720000000072, type: 7, name: NULL
VUID-vkResetFences-pFences-01123(ERROR / SPEC): msgNum: 0 - VkFence 0x750000000075[] is in use. The Vulkan spec states: Each element of pFences must not be currently associated with any queue command that has not yet completed execution on that queue (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkResetFences-pFences-01123)
    Objects: 1
        [0] 0x750000000075, type: 7, name: NULL
VUID-vkResetFences-pFences-01123(ERROR / SPEC): msgNum: 0 - VkFence 0x7c000000007c[] is in use. The Vulkan spec states: Each element of pFences must not be currently associated with any queue command that has not yet completed execution on that queue (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkResetFences-pFences-01123)
    Objects: 1
        [0] 0x7c000000007c, type: 7, name: NULL
VUID-vkResetFences-pFences-01123(ERROR / SPEC): msgNum: 0 - VkFence 0x790000000079[] is in use. The Vulkan spec states: Each element of pFences must not be currently associated with any queue command that has not yet completed execution on that queue (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkResetFences-pFences-01123)
    Objects: 1
        [0] 0x790000000079, type: 7, name: NULL
```
repeat many times

I can make video of it if you want

>nobody has reported similar issues.

maybe no one uses Vulkan at all, bugs [I personally found](https://community.khronos.org/c/vulkan/vulkan-drivers/49) in Vulkan drivers on very basic examples(include Khronos samples) make Vulkan very questionable for me, or driver developers make it this way to force people to use DX12 and new GPU

**Comment by TheMostDiligent** [comment]
Thank you for the very detailed investigation of the problem. This issue should be an example of what an ideal description of a problem should look like.

It appears there might be a problem with how the driver reports the fence completion status. Diligent relies on fences to manage the lifetimes of resources. Other applications most likely use triple or double buffering instead and don't use fences, which is why they may work.
Here is the fence managing logic works:
- A used fence is [only disposed](https://github.com/DiligentGraphics/DiligentCore/blob/master/Graphics/GraphicsEngineVulkan/src/FenceVkImpl.cpp#L79) when its status is `VK_SUCCESS`. 
- The fence is [reset next time](https://github.com/DiligentGraphics/DiligentCore/blob/master/Graphics/GraphicsEngineVulkan/src/VulkanUtilities/VulkanFencePool.cpp#L57) it is requested, and only singled fences end up in `m_FencePool` list

So the logic appears to be correct, and it seems to work on all platforms including my Linux machine with NV GTX970 GPU.


> maybe no one uses Vulkan at all

In fact there are quite a few customers that use Linux including for production applications and they haven't reported any problems with Vulkan on Linux.

The problem could be somehow related to your relatively old GPU (though obviously everything should still work). It would be very interesting to try to run the apps on Windows on the same GPU.

Another thing to try I can think of is to add `WaitForIdle` commands to see if it makes any difference.

**Comment by danilw** [comment]
Update with more testing:

### Windows version

I build `Tutorial17_MSAA.exe` in VS 16 (Win10)

**on WIndows** DX11, DX12, OGL, and Vulkan work without any problems, I can launch many windows(app) with no lags
**VSync also works**, default fps 2000+(no VSynk)

**on Linux under Wine and DXVK 1.6** that Win10 exe build launched in Wine:
**DX11** does not work, crash on initialization(before window creation)
**OGL** work
**Vulkan** work without lags(X11 does not lag) **VSynk works**, fps 2000+ by default, and 60 with VSynk

After I launch native(linux) `Tutorial17_MSAA` at the same time with `Tutorial17_MSAA.exe` in Wine (left WIne, right Linux native)
![1](https://user-images.githubusercontent.com/24825887/89853905-37c08880-db9b-11ea-9c68-0aed9cf7e523.png)

On Wine `Tutorial17_MSAA.exe` VSynk drop FPS to 30 (on screenshot it not displayed because UI start laging after launching native version), Native version ignore VSynk and FPS at 50 always

**After closing** Native `Tutorial17_MSAA` and Wine version, I can not launch any of it, 
bots Wine and Native spam same message
```
Diligent Engine: Warning: Space in dynamic heap is almost exausted. Allocation forced idling the GPU. Increase the size of the heap by setting EngineVkCreateInfo::DynamicHeapSize to a greater value or optimize dynamic resource usage
Diligent Engine: Warning: Space in dynamic heap is almost exausted. Allocation forced idling the GPU. Increase the size of the heap by setting EngineVkCreateInfo::DynamicHeapSize to a greater value or optimize dynamic resource usage
Diligent Engine: Warning: Space in dynamic heap is almost exausted. Allocation forced idling the GPU. Increase the size of the heap by setting EngineVkCreateInfo::DynamicHeapSize to a greater value or optimize dynamic resource usage

```

**And I can not launch any of** `DiligentSamples/Tutorials` 
**Tutorials only** when every of `DiligentSamples/Samples/` still work
To reboot, I can not launch any Tutorial. Always a black window.


### WaitForIdle

>Another thing to try I can think of is to add WaitForIdle commands to see if it makes any difference.

Sleep/wait to any of functions does not change anything, I did change source code of `Tutorial03_Texturing` no effect

After adding a few debug messages(debug using cout), I see that 
```
void Tutorial03_Texturing::Update(double CurrTime, double ElapsedTime)
```
function `Update()` called once, then huge lag when everything freeze because black window bug, and it continues calling `Update()` after that, and spam error message to console

>It appears there might be a problem with how the driver reports the fence completion status. Diligent relies on fences to manage the lifetimes of resources. Other applications most likely use triple or double buffering instead and don't use fences, which is why they may work.

Yes. The reason is GPU ignore waiting for Fence or somehow X11 surface make it broken.
(I still think it can be X11 surface problem, other surfaces like Wayland may not have this problem, like WIN32 surface work correct in Windows)

**So the result is:**
Only `DiligentSamples/Tutorials`  broken on my GPU in Linux, broken till reboot
When `DiligentSamples/Samples/` still work (only bug with out of memory)
On Windows no bugs.

Can be closed, I will not gonna fix `Tutorials` code, sorry.

**Comment by TheMostDiligent** [comment]
> somehow X11 surface make it broken.

In Vulkan Diligent [uses XCB surface](https://github.com/DiligentGraphics/DiligentTools/blob/master/NativeApp/src/Linux/LinuxMain.cpp#L218), so maybe X11 will actually work. You may try to init [Vulkan in X11 mode](https://github.com/DiligentGraphics/DiligentTools/blob/master/NativeApp/src/Linux/LinuxMain.cpp#L430) (that should not be too difficult), if you have time.

**Comment by danilw** [comment]
Look like kernel 5.8 [fix](https://bugzilla.kernel.org/show_bug.cgi?id=207383) Ryzend and amdgpu problem.
**So I did update do Nvidia 450.57 driver.**

Everything work the same, no changes. Debug and validation layer output are the same, and VSync check has no effect.
![1](https://user-images.githubusercontent.com/24825887/89962000-208da380-dc4c-11ea-90ff-634f80e7dd61.png)

>Only DiligentSamples/Tutorials broken on my GPU in Linux, broken till reboot
When DiligentSamples/Samples/ still work (only bug with out of memory)


**about surfaces:**

>In Vulkan Diligent uses XCB surface
>You may try to init Vulkan in X11 mode (that should not be too difficult), if you have time.

as I understand you tell me that I can rewrite these Samples to use XLIB surface, base on OpenGL initialization?

I checked, I see [SwapChainVkImpl.cpp#L124](https://github.com/DiligentGraphics/DiligentCore/blob/master/Graphics/GraphicsEngineVulkan/src/SwapChainVkImpl.cpp#L124)
look like this engine can support XLIB surface, but [GraphicsEngineVulkan/CMakeLists.txt#L260](https://github.com/DiligentGraphics/DiligentCore/blob/master/Graphics/GraphicsEngineVulkan/CMakeLists.txt#L260)
```
set(PRIVATE_COMPILE_DEFINITIONS VK_USE_PLATFORM_XCB_KHR=1 VK_USE_PLATFORM_XLIB_KHR=1)
```
look like "this support hidden" for some reason
I tried removing `VK_USE_PLATFORM_XCB_KHR=1` and rebuilding, it can be compiled, but does not work because XLIB surface does not support by Samples and Tutorials.

than I saw this [SampleAppLinux.cpp#L67](https://github.com/DiligentGraphics/DiligentSamples/blob/master/SampleBase/src/Linux/SampleAppLinux.cpp#L67)
look like XLIB support not included to Samples, and I need to make it my self, as I understand I need to change some code in Engine and/or Samples, I did not found fast way to do it, maybe im missing something

I have other projects to do now, I do not want to make it sorry.

it can be DE conflict with X11 or XCB or something else, but other Vulkan Samples/games/even DXVK work fine, my specs
OS openSUSE Tumbleweed (everything default)
DE XFCE4
GPU Nvidia 750

if its only my problem can be closed

**Comment by danilw** [comment]
il update latter today if I make it work on X11, with more info

**Comment by danilw** [comment]
Final update;
Kernel 5.8 [fix](https://bugzilla.kernel.org/show_bug.cgi?id=207383) Ryzen and amdgpu problem.
**So I did update do Nvidia 450.57 driver.**

Everything work the same, no changes. Debug and validation layer output are the same, and VSync check has no effect.
![1](https://user-images.githubusercontent.com/24825887/89962000-208da380-dc4c-11ea-90ff-634f80e7dd61.png)

>In Vulkan Diligent uses XCB surface, so maybe X11 will actually work. You may try to init Vulkan in X11 mode (that should not be too difficult), if you have time.

I tried to change `Tutorial00_HelloLinux.cpp` and `LinuxMain.cpp`
after changing `TheApp->OnGLContextCreated(display, win);` as you say
to `TheApp->InitVulkan_X11(display, win);` 
and adding to [SampleAppLinux.cpp](https://github.com/DiligentGraphics/DiligentSamples/blob/master/SampleBase/src/Linux/SampleAppLinux.cpp)
```
    virtual bool InitVulkan_X11(Display* display, Window window) override final
    {
        try
        {
            m_DeviceType = RENDER_DEVICE_TYPE_VULKAN;
            LinuxNativeWindow LinuxWindow;
            LinuxWindow.pDisplay = display;
            LinuxWindow.WindowId = window;
            InitializeDiligentEngine(&LinuxWindow);
            const auto& SCDesc = m_pSwapChain->GetDesc();
            m_pImGui.reset(new ImGuiImplLinuxX11(m_pDevice, SCDesc.ColorBufferFormat, SCDesc.DepthBufferFormat, SCDesc.Width, SCDesc.Height));
            InitializeSample();
            return true;
        }
        catch (...)
        {
            return false;
        }
    }
```

I have crash on creating swapchain [SwapChainVkImpl.cpp#L453](https://github.com/DiligentGraphics/DiligentCore/blob/master/Graphics/GraphicsEngineVulkan/src/SwapChainVkImpl.cpp#L453)

I do not want to continue debugging this my problem, sorry

maybe someone who need to make it work will do this job

I close bugreport
