### ISSUE TITLE
Tutorial05_TextureArray and Tutorial10_DataStreaming produce corrupted visual results on Samsung Galaxy Core Prime

### ISSUE THREAD

**Issue by DiligentGraphics** [DiligentGraphics/DiligentSamples#6]

**Comment by DiligentGraphics** [comment]
@dolphineye could you please attach a screenshot?

**Comment by dolphineye** [comment]
I'll send you screenshots ASAP. The other tutorials are OK except those that rely on non-OpenGL ES 3.0 features (tesselation, geometry shaders etc.) which is totally normal (hence not a bug).

**Comment by DiligentGraphics** [comment]
You can drag-and-drop images right here. For some reason there is no button to attach an image, but drag-and-drop works fine.

**Comment by dolphineye** [comment]
Tutorial05_TextureArray

![20190222_171841](https://user-images.githubusercontent.com/31071122/53255572-35781f00-36c6-11e9-9c86-6afab3bc0303.jpg)

Tutorial10_DataStreaming 

![20190222_171934](https://user-images.githubusercontent.com/31071122/53255666-5f314600-36c6-11e9-91c7-ad3a47b1c0d4.jpg)

I just noticed that both these tutorials randomly crash on startup. I don't have time to attach the crash log files for now, I'll to do that later, Monday tops.

**Comment by DiligentGraphics** [comment]
Hmm... Is there anything in the logcat? Maybe a crash log would give a clue to what the problem is...

**Comment by dolphineye** [comment]
Hopefully, I'll post the logcat output on Monday when I get back to the office ;)

**Comment by DiligentGraphics** [comment]
Tutorial05 uses texture copy functionality which is emulated on old device via rendering to textures. I tested it and it seemed to work ok on desktop GL without separate shaders, but there could be an issue on Android.

**Comment by dolphineye** [comment]
Maybe it's just a driver issue on the Samsung Core Prime - which was a low end device in 2015. AFAIK the OpenGL ES driver on that device is one of the worst I've even seen - that why I keep it for testing my worst case scenarios.

Maybe I should try to find out other test devices to see if these issues occur on all OpenGL ES 3.0 compatible devices or just the Core Prime.

**Comment by DiligentGraphics** [comment]
Could be a driver bug - it takes the same path on iPhone and works fine.

**Comment by DiligentGraphics** [comment]
@dolphineye Is this problem still relevant for you?

**Comment by dolphineye** [comment]
Honestly, I didn't have the time to investigate further since my last post. You can close the issue if you want. I'll open a new issue if that's still relevant in the future. If that OK for you?

**Comment by DiligentGraphics** [comment]
Ok, will close this for now. Certainly feel free to reopen or create a new issue if you get back to this problem.
