### ISSUE TITLE
Android Samples do not run in Simulator

### ISSUE THREAD

**Issue by TheMostDiligent** [DiligentGraphics/DiligentSamples#65]
It has been reported that Android samples crash in simulator. This needs to be verified.

**Comment by vladimirlukyanov** [comment]
Yes, i confirm – it's not working and giving following error.
![unknown](https://user-images.githubusercontent.com/2518266/129470414-6cd83afa-8896-4712-93df-a84248b247f8.png)

**Comment by vladimirlukyanov** [comment]
My suggestion here, that Android simulator is only support OpenGL ES 2.0, not 3.1.
That's why it might be failing.
https://stackoverflow.com/questions/24874066/does-the-android-emulator-support-opengl-es-3-0

**Comment by TheMostDiligent** [comment]
This may be the case. Diligent needs GLES3.0, it does not support GLES2.0

**Comment by azhirnov** [comment]
By default Android Emulator uses GLES2.0.
To enable GLES3.0 you need to run emulator, then press ... -> Settings -> Advanced.
In this tab select `OpenGL ES renderer`:  `Desktop native OpenGL` works well, `SwiftShader` works with GL errors.
`OpenGL ES API level` must be switched to `Renderer maximum (up to OpenGL ES 3.1)`.

![android](https://user-images.githubusercontent.com/2104977/130670641-68a36e41-9a1a-4291-9a1c-f85b91507e47.png)

**Comment by TheMostDiligent** [comment]
Please get the latest and follow the instructions above. The samples should now run in the simulator


![image](https://user-images.githubusercontent.com/61806567/131266753-1f992e97-5aeb-48ef-93d0-c8629d1fd062.png)
