### ISSUE TITLE
Shadows sample doesn't work properly on Mac with Vulkan (MoltenVK) backend

### ISSUE THREAD

**Issue by tintifax89** [DiligentGraphics/DiligentSamples#79]
I'm having issues with the Shadows sample application. The visual output doesn't look reasonable when using Vulkan (MoltenVK) backend on my Mac. The shadows in the scene move among the scene by moving/rotating the camera. When using OpenGL backend it works properly though. The attached video shows the Shadows sample app using Vulkan (MoltenVK) backend to illustrate the issue.

Details about my configuration:
- MacBook Pro (16-Inch, 2019)
- MacOS Big Sur 11.6
- Built with XCode 13.1
- GPU: AMD Radeon Pro 5500M 4 GB
- DiligentEngine Commit ID 7f19fbc4e29f07acf2d8a69ff1a204c3f0d1a33e
- Vulkan SDK version 1.2.189.0

https://user-images.githubusercontent.com/2699651/142402145-d91788e5-bd4f-4f15-886c-e1c9e1d55468.mov

**Comment by TheMostDiligent** [comment]
@tintifax89 Can you try to test this with the latest SDK? The sample works fine on Intel and M1 GPUs. We don't have MacBooks with AMD GPUs.

**Comment by tintifax89** [comment]
Just tested it with the most recent DiligentEngine master and it still had the same issue. Afterwards I also updated my MoltenVK version which fixed it. Thanks for your efforts!
