### ISSUE TITLE
Configure Copy Files build phase in iOS Xcode project from CMake

### ISSUE THREAD

**Issue by DiligentGraphics** [DiligentGraphics/DiligentSamples#9]
At the moment, it is required to manually add Copy files build phase to iOS Xcode project generated by CMake to bundle and code-sign MoltenVK dylib, which is inconvenient.
See also [stackoverflow question](https://stackoverflow.com/questions/55410066/define-xcode-copy-files-build-phase-in-cmake).

**Comment by DiligentGraphics** [comment]
https://stackoverflow.com/questions/30430968/add-xcode-build-phase-via-cmake

**Comment by TheMostDiligent** [comment]
This is not relevant anymore as Diligent now links statically with MoltenVk library
